#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname $0)/functions"

[[ ! -f "$PSQL_ROOT/db_$1" ]] && exit 0
load_container_id
[[ -z "$PSQL_ID" ]] && dokku psql:start
exit 0
